import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { signIn, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

export default function Auth({ fallbackData }) {
  const { data: session, status } = useSession()
  return (
    <div className={styles.container}>
      <Head>
        <title>HackMedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
    <div className={styles.signForm}>
        <h2>Leave a message. </h2>
        <p>
          Leave a message below for me, and all future visitors of this site!
        </p>
        {!session && (
          <div className={styles.logoutState}>
              <h1>Welcome!</h1>
              <p>Hey there, to contine any futher, we&apos;re going to need you to sign in below.</p>
            <Link href="/api/auth/signin/github" passHref>
          <button
            onClick={(e) => {
              e.preventDefault();
              signIn('github');
            }}
          >
            Sign in with GitHub.
          </button>
          </Link>
          </div>
        )}

        {session?.user && (
        <h1>hello there!</h1>
            )
          })
        </div>
    </div>
  </div>
  )
}
