import Head from 'next/head';
import Link from 'next/link';
import { signOut, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter()
    const { data: session, status } = useSession({
      required: true,
    onUnauthenticated() {
      router.push('/auth');
      },
    })
  return (
    <div>
      <Head>
        <title>HackMedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hi</h1>
      {session?.user && (
        <div>
          <h1 className="">Welcome to hackMedia!</h1>
          <Link href="/api/auth/signOut" passHref>
          <button
          onClick={(e) => {
            e.preventDefault();
            signOut();
          }}
        >Sign out</button>
        </Link>
        </div>
        )}
    </div>
  )
}