import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { signIn } from 'next-auth/react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HackMedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.title}>
          Welcome to HackMedia!
        </h1>
        <h2>The name will probably change...</h2>
        <Link href="/api/auth/signin" passHref>
          <button
          onClick={(e) => {
            e.preventDefault();
            signIn('github');
          }}
        >Sign in with GitHub</button>
        </Link>
    </div>
  )
}
