import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { signIn, useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter()
    const { data: session, status } = useSession({
      required: true,
    onUnauthenticated() {
      router.push('/auth');
      },
    })
  return (
    <div className={styles.container}>
      <Head>
        <title>HackMedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>hi</h1>
      if (status === "authenticated") {
     <p>Welcome to HackMedia!</p>
    }

    </div>
  )
}